name: Convert jupyter notebook readme into markdown 

on: push

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Install dependecies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install -d # Install all dependencies, including development ones

    - name: convert to markdown
      run: pipenv run jupyter nbconvert README.ipynb --to markdown

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Generate README.md from README.ipynb