name: Convert jupyter notebook readme into markdown 

on: push

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install jupyter
      run : python -m pip install --upgrade jupyter

    - name: convert to markdown
      run: python run jupyter nbconvert README.ipynb --to markdown

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Generate README.md from README.ipynb